apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: tienda
spec:
  replicas: 2 # alta disponibilidad
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ethanr25/tienda-backend:latest
          imagePullPolicy: Always
          command: ["sh", "-c", "node app.js || sleep 3600"]
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: ethanuser
            - name: DB_PASS
              value: app123_
            - name: DB_NAME
              value: tienda_parcial
          ports:
            - containerPort: 3001
