apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-backend
  template:
    metadata:
      labels:
        app: tienda-backend
    spec:
      containers:
        - name: backend
          image: ethanr25/tienda-backend:latest
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "ethanuser"
            - name: DB_PASSWORD
              value: "app123_"
            - name: DB_NAME
              value: "tienda_parcial"
          ports:
            - containerPort: 3001
