apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-frontend
  template:
    metadata:
      labels:
        app: tienda-frontend
    spec:
      containers:
        - name: frontend
          image: ethanr25/tienda-frontend:latest
          ports:
            - containerPort: 80
