name: Rollout to Minikube

on:
  workflow_run:
    workflows:
      - "Build & Deploy Backend"
      - "Build & Deploy Frontend"
    types:
      - completed

jobs:
  rollout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Iniciar Minikube si no está corriendo
        shell: powershell
        run: |
          $status = minikube status --format '{{.Host}}'
          if ($status -ne "Running") {
            minikube start --driver=docker
          }

      - name: Reiniciar deployments con minikube kubectl
        shell: powershell
        run: |
          minikube status
          minikube kubectl -- rollout restart deployment backend
          minikube kubectl -- rollout restart deployment frontend
