name: Rollout to Minikube

on:
  workflow_run:
    workflows:
      - "Build & Deploy Backend"
      - "Build & Deploy Frontend"
    types:
      - completed

jobs:
  rollout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v3

      - name: Preparar kubeconfig (Windows)
        shell: powershell
        run: |
          if (!(Test-Path "$env:USERPROFILE\.kube")) {
            New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.kube" | Out-Null
          }
          Set-Content -Path "$env:USERPROFILE\.kube\config" -Value "${{ secrets.KUBECONFIG }}"

      - name: Reiniciar deployments
        shell: bash
        run: |
          kubectl rollout restart deployment backend
          kubectl rollout restart deployment frontend
