name: Rollout to Minikube

on:
  workflow_run:
    workflows:
      - "Build & Deploy Backend"
      - "Build & Deploy Frontend"
    types:
      - completed

jobs:
  rollout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v3

      - name: Preparar kubeconfig (Windows)
        shell: powershell
        run: |
          $kubeDir = "$env:USERPROFILE\.kube"
          if (!(Test-Path $kubeDir)) {
            New-Item -ItemType Directory -Force -Path $kubeDir | Out-Null
          }

          Set-Content -Path "$kubeDir\config" -Value "${{ secrets.KUBECONFIG }}"

      - name: Reiniciar deployments
        shell: powershell
        run: |
          kubectl rollout restart deployment/backend
          kubectl rollout restart deployment/frontend
