name: Rollout to Minikube

on:
  workflow_run:
    workflows:
      - "Build & Deploy Backend"
      - "Build & Deploy Frontend"
    types:
      - completed

jobs:
  rollout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Bajar cÃ³digo
        uses: actions/checkout@v3

      - name: Configurar kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Reiniciar deployments
        run: |
          kubectl rollout restart deployment backend
          kubectl rollout restart deployment frontend
